package application;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;



import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class AddAppointmentScreenController implements Initializable {
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private ComboBox docMenu;
	@FXML
	private Label doc_excuselbl;
	@FXML
	private Label day_excuselbl;
	@FXML
	private ComboBox timesMenu;
	@FXML
	private Label doc_excuselbl1;
	@FXML
	private Label errorLabel;
	@FXML
	private ComboBox dateMenu;
	
	 SystemManager sys = SystemManager.Singleton();
	 
	 
	 

	// Event Listener on ComboBox[#docMenu].onAction
	@FXML
	public void doctorNamesSelect(ActionEvent event) {
		// TODO Autogenerated
		
		/*ArrayList<String> arrayList=new ArrayList<String>();
		
		ObservableList<String> list= FXCollections.observableArrayList(arrayList);
		dateMenu.setItems(list);*/
	}
	// Event Listener on ComboBox[#timesMenu].onAction
	@FXML
	public void timesMenuSelect(ActionEvent event) {
		String doc=docMenu.getSelectionModel().getSelectedItem().toString();
		String date=dateMenu.getSelectionModel().getSelectedItem().toString();
		if(doc!=null &&date!=null) {
			
			timesMenu.setItems( FXCollections.observableArrayList(sys.DisplaySchedule(doc, date)));
			
		}else {
			errorLabel.setText("please fill doctor and date boxes");
		}
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void AddAppointFunc(ActionEvent event) {
		String doc=docMenu.getSelectionModel().getSelectedItem().toString();
		String date=dateMenu.getSelectionModel().getSelectedItem().toString();
		String time=timesMenu.getSelectionModel().getSelectedItem().toString();
		if(date!=null && time!=null && doc!=null)
		sys.secertaryAddApointment(date, time, doc);
		else 
			errorLabel.setText("please fill all boxes");
	}
	
	// Event Listener on ComboBox[#dateMenu].onAction
	@FXML
	public void dateMenuSelect(ActionEvent event) {
		String doc=docMenu.getSelectionModel().getSelectedItem().toString();
		String date=dateMenu.getSelectionModel().getSelectedItem().toString();
	if(doc!=null &&date!=null) {
			
			timesMenu.setItems( FXCollections.observableArrayList(sys.DisplaySchedule(doc, date)));
			
		}else {
			errorLabel.setText("please fill doctor and date boxes");
		}

	}
	
   
	public void initialize(URL url,ResourceBundle rb) {
		
		//	ObservableList<String>list=FXCollections.observableArrayList(sys.docNamesList(sys.getDoctors()));
			
			docMenu.setItems(FXCollections.observableArrayList(sys.docNamesList(sys.getDoctors())));
			dateMenu.setItems(FXCollections.observableArrayList("Saturday","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday"));
			//timesMenu.setItems(FXCollections.observableArrayList("01:00","02:00","03:00","04:00","05:00"));
			
			
		}


}
