package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class patientMedicalHistoryController implements Initializable  {
	SystemManager sys = SystemManager.Singleton();
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private ComboBox patientList;
	@FXML
	private Button displaybtn;
	@FXML
	private ListView medicalHistoryList;
	@FXML
	private Label displaySuccesslbl;
	@FXML
	private Label errorLabel;
	

	// Event Listener on ComboBox[#patientList].onAction
	@FXML
	public void patientSelectSchedFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#displaybtn].onAction
	@FXML
	public void displayMedicalPatientHistoryFunc(ActionEvent event) {
		String pat=patientList.getSelectionModel().getSelectedItem().toString();
		if(pat!=null) {
			medicalHistoryList.getItems().add(sys.doctorGetPatientMedicalHistory(pat).getTreatment());
		}else
			errorLabel.setText("Please Enter Patient's Name");
	}
	public void initialize(URL url,ResourceBundle rb) {
		
		//	ObservableList<String>list=FXCollections.observableArrayList(sys.docNamesList(sys.getDoctors()));
			
			patientList.setItems(FXCollections.observableArrayList(sys.patNamesList(sys.getPatients())));
			
			
			
			
		}
}
