package UIControllers;

import javafx.fxml.FXML;

import java.util.ArrayList;

import application.SystemManager;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class AddAppointmentScreenController {
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private ComboBox docMenu;
	@FXML
	private Label doc_excuselbl;
	@FXML
	private Label day_excuselbl;
	@FXML
	private ComboBox timesMenu;
	@FXML
	private Label doc_excuselbl1;
	@FXML
	private Label errorLabel;
	@FXML
	private ComboBox dateMenu;
	
	 SystemManager sys = SystemManager.Singleton();
	 
	 
	 

	// Event Listener on ComboBox[#docMenu].onAction
	@FXML
	public void doctorNamesSelect(ActionEvent event) {
		// TODO Autogenerated
		
		/*ArrayList<String> arrayList=new ArrayList<String>();
		
		ObservableList<String> list= FXCollections.observableArrayList(arrayList);
		dateMenu.setItems(list);*/
	}
	// Event Listener on ComboBox[#timesMenu].onAction
	@FXML
	public void timesMenuSelect(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void AddAppointFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#dateMenu].onAction
	@FXML
	public void dateMenuSelect(ActionEvent event) {
		// TODO Autogenerated
	}
}
