package UIControllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class displayScheduleController {
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private ComboBox docMenuSched;
	@FXML
	private ComboBox daysMenu;
	@FXML
	private Button displaybtn;
	@FXML
	private ListView docList;
	@FXML
	private Label displaySuccesslbl;

	// Event Listener on ComboBox[#docMenuSched].onAction
	@FXML
	public void doctorSelectSchedFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#daysMenu].onAction
	@FXML
	public void dayScheduleSelectFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#displaybtn].onAction
	@FXML
	public void displayScheduleFunc(ActionEvent event) {
		// TODO Autogenerated
	}
}
