package UIControllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class editScheduleController {
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private Button confirmbtn;
	@FXML
	private ComboBox doctorCombBox;
	@FXML
	private ComboBox dateCombBox;
	@FXML
	private ComboBox timeCombBox;
	@FXML
	private Label errorLabel;

	// Event Listener on Button[#confirmbtn].onAction
	@FXML
	public void confirmFunction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#doctorCombBox].onAction
	@FXML
	public void doctorListFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#dateCombBox].onAction
	@FXML
	public void dateListFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#timeCombBox].onAction
	@FXML
	public void timeListFunc(ActionEvent event) {
		// TODO Autogenerated
	}
}
