package UIControllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class initiateExcuseController {
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private ComboBox docExcuseMenu;
	@FXML
	private Label doc_excuselbl;
	@FXML
	private Label day_excuselbl;
	@FXML
	private ComboBox daysMenu;
	@FXML
	private Button excuse_confirmbtn;
	@FXML
	private Label errorLabel;

	// Event Listener on ComboBox[#docExcuseMenu].onAction
	@FXML
	public void doctorExcuseSelect(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#daysMenu].onAction
	@FXML
	public void dayExcuseSelect(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#excuse_confirmbtn].onAction
	@FXML
	public void excuseConfirmFunc(ActionEvent event) {
		// TODO Autogenerated
	}
}
