package UIControllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

public class patientMedicalHistoryController {
	@FXML
	private AnchorPane operationScreenShower;
	@FXML
	private ComboBox patientList;
	@FXML
	private Button displaybtn;
	@FXML
	private ListView medicalHistoryList;
	@FXML
	private Label displaySuccesslbl;

	// Event Listener on ComboBox[#patientList].onAction
	@FXML
	public void patientSelectSchedFunc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#displaybtn].onAction
	@FXML
	public void displayMedicalPatientHistoryFunc(ActionEvent event) {
		// TODO Autogenerated
	}
}
